/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaeuronew;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;


public class App {
        private static String getapi;
        public static String getapi() {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
         .uri(URI.create("http://api.napiarfolyam.hu"))
         .build();
        String response = client.sendAsync(request, BodyHandlers.ofString())
              .thenApply(HttpResponse::body)
              .join(); 
        return response;
            
    }
    public static void GetEuroprice(){
        String sell = "";
        String buy = "";
        getapi = getapi();
        getapi = getapi.replace("\n", "").replace("\r", "").replace("\t", "").replace("<", "").replace(">", "").replace("/", "");
		int i = getapi.indexOf("otp");
        if(i<0)
            System.out.println("string not found");
        else{
            String subgetapi = getapi.substring(i, getapi.length());
            
            int j = subgetapi.indexOf("EUR");
                String ssubgetapi = subgetapi.substring(j, subgetapi.length());
                    int k = ssubgetapi.indexOf("vetel");
                    if(k<0)
                        System.out.println("string not found");
                    else{
                        buy = ssubgetapi.substring(k+5, k+11);
                        int l = ssubgetapi.indexOf("eladas");
                        if(l<0)
                             System.out.println("string not found");
                        else{
                            sell = ssubgetapi.substring(l+6, l+12);
                            System.out.println(String.format("Euro\nBuy: %sFt\nSell: %sFt", buy,sell));
                            
                        }
                    }
                   
                }
            }    
    public static void main(String[] args) {
       GetEuroprice();
    }   
}